### ISSUE TITLE
设计的很好看, 我可以借鉴一下吗?

### ISSUE THREAD

**Issue by LonelyLiaR** [Nbsaw/dura#11]
文化人的事, 能算抄么?

![h s 3 pyq7ganhz_evqp92r](https://user-images.githubusercontent.com/12504732/42684413-9c2d678c-86c2-11e8-9b45-b0dbe6b5e93d.jpg)

**Comment by Nbsaw** [comment]
@LonelyLiaR 哈哈 你确定不是随便弄的

**Comment by LonelyLiaR** [comment]
HomePage的简约风很酷.
LabelsPage的就有点花里胡哨了.
我打算做成[这个老哥](https://rauchg.com/essays)的样子.

**Comment by Nbsaw** [comment]
都是在实践一些东西 才弄的

**Comment by LonelyLiaR** [comment]
持续关注着nbsaw大神的成神之路. 加油. 👍

**Comment by LonelyLiaR** [comment]
https://lonelyliar.github.io/#/
