### ISSUE TITLE
移动端炸裂

### ISSUE THREAD

**Issue by LonelyLiaR** [Nbsaw/dura#12]
我觉得移动端可以隐藏左边那栏.
![phk 33e5zrd4iynz49 mckn](https://user-images.githubusercontent.com/12504732/43309006-060e1162-91b6-11e8-8767-7f05b097ed2a.png)

**Comment by Nbsaw** [comment]
因为没做自适应 。。。

**Comment by Nbsaw** [comment]
请用户侧屏 谢谢  🌚
